Repository BloopAI/bloop, pull requests merged in 2023-11, with the labels that each got.

#1069 Login changes
  client/src/components/AddStudioContext/index.tsx
  client/src/components/SeparateOnboardingStep/DialogText/index.tsx
  client/src/locales/en.json
  client/src/locales/es.json
  client/src/locales/it.json
  client/src/locales/ja.json
  client/src/locales/zh-CN.json
  client/src/pages/HomeTab/AddRepos/AddCodeStudio/index.tsx
  client/src/pages/HomeTab/AddRepos/GithubReposStep/index.tsx
  client/src/pages/HomeTab/AddRepos/GoBackButton/index.tsx
  client/src/pages/HomeTab/AddRepos/LocalReposStep/index.tsx
  client/src/pages/HomeTab/AddRepos/PublicGithubReposStep/index.tsx
  client/src/pages/HomeTab/AddRepos/index.tsx
  client/src/pages/Onboarding/Desktop/FeaturesStep/Feature.tsx
  client/src/pages/Onboarding/Desktop/FeaturesStep/index.tsx
  client/src/pages/Onboarding/Desktop/UserForm/Step1.tsx
  client/src/pages/Onboarding/Desktop/UserForm/Step2.tsx
  client/src/pages/Onboarding/Desktop/UserForm/index.tsx
  client/src/pages/Onboarding/Desktop/index.tsx
  client/src/pages/Onboarding/SelfServe/index.tsx
  client/src/pages/Onboarding/SelfServeStep/index.tsx
  client/src/pages/Onboarding/UserForm/index.tsx
  client/src/pages/Onboarding/index.tsx
Labels: frontend

#1123 Fix breadcrumbs in doc search modal
  client/src/pages/StudioTab/AddDocsModal/PagesWithPreview/index.tsx
Labels: bug, frontend

#1141 Better notifications on startup failure
  apps/desktop/src-tauri/src/backend.rs
  apps/desktop/src/App.tsx
  apps/desktop/src/SplashScreen.tsx
Labels: bug
