Repository BloopAI/bloop, pull requests merged in 2023-01, with the labels that each got.

#53 Replace `tract-onnx` with `ort`
  Cargo.lock
  server/bleep/Cargo.toml
  server/bleep/src/lib.rs
  server/bleep/src/semantic.rs
Labels: enhancement, optimisation

#52 Better recovery after shutdown
  server/bleep/src/state.rs
Labels: bug, backend

#58 Update OpenAI API call to add tracking `user_id` field
  client/src/components/CodeBlock/SemanticSearch/index.tsx
  client/src/hooks/useAnalytics.ts
  client/src/pages/NLResults/index.tsx
  client/src/services/api.ts
  client/src/types/api.ts
  server/bleep/src/webserver/answer.rs
Labels: enhancement

#119 Add Docker caching to backend and frontend builds
  .dockerignore
  .github/workflows/docker.yml
  Dockerfile
Labels: enhancement, backend

#135 Move all configuration items to be provisioned from the config
  Cargo.lock
  server/bleep/Cargo.toml
  server/bleep/src/bin/bleep.rs
  server/bleep/src/config.rs
  server/bleep/src/lib.rs
Labels: enhancement, backend

#141 Unify cache dirs for Tauri app
  apps/desktop/src-tauri/src/backend.rs
  server/bleep/src/state.rs
Labels: bug, backend

#142 Limit maximum number of parallel authentication sessions
  Cargo.lock
  server/bleep/Cargo.toml
  server/bleep/src/webserver/aaa.rs
Labels: bug, backend

#134 Make backend feature-matrix enforced
  apps/desktop/src-tauri/src/backend.rs
  server/bleep/src/bin/bleep.rs
  server/bleep/src/env.rs
  server/bleep/src/lib.rs
  server/bleep/src/remotes/poll.rs
  server/bleep/src/webserver.rs
Labels: enhancement, backend

#146 Merge CLI arguments with config-supplied values, prefer CLI args
  apps/desktop/src-tauri/src/backend.rs
  server/bleep/src/bin/bleep.rs
  server/bleep/src/config.rs
  server/bleep/src/lib.rs
  server/bleep/src/state.rs
Labels: enhancement, backend

#147 Allow unlinking Github user profile from local app
  server/bleep/src/webserver.rs
  server/bleep/src/webserver/github.rs
Labels: enhancement, backend
