Repository BloopAI/bloop, pull requests merged in 2023-02, with the labels that each got.

#155 Lock cargo CI workflows
  .github/workflows/server-test.yml
  .github/workflows/tauri-release.yml
  .github/workflows/tauri-test.yml
  Dockerfile
Labels: backend, optimisation

#156 Make sure `/api/health-check` fails with 500 if qdrant doesn't work
  server/bleep/src/semantic.rs
  server/bleep/src/webserver.rs
Labels: bug, backend

#160 Don't start bloop if `qdrant_url` is invalid
  apps/desktop/src-tauri/src/backend.rs
  server/bleep/benches/indexes.rs
  server/bleep/src/config.rs
  server/bleep/src/lib.rs
  server/bleep/src/semantic.rs
  server/bleep/src/webserver.rs
Labels: bug, backend

#173 More docker caching
  Cargo.lock
  Dockerfile
Labels: backend

#153 Handle disconnect/remote repo deletion
  client/src/components/RepoCard/index.tsx
  client/src/components/Settings/Repositories/index.tsx
  client/src/pages/Home/ReposSection/index.tsx
  client/src/services/api.ts
  client/src/types/general.ts
  server/bleep/src/background.rs
  server/bleep/src/remotes.rs
  server/bleep/src/remotes/github.rs
  server/bleep/src/remotes/poll.rs
  server/bleep/src/state.rs
Labels: backend

#177 Bump dependencies
  Cargo.lock
Labels: bug, backend

#178 Ignore our repository stash when scanning local directories
  server/bleep/src/remotes.rs
  server/bleep/src/state.rs
  server/bleep/src/webserver/repos.rs
Labels: bug, backend

#182 Remove repositories from indexes
  server/bleep/src/background.rs
  server/bleep/src/state.rs
  server/bleep/src/webserver.rs
  server/bleep/src/webserver/repos.rs
Labels: bug, backend

#203 Flake fix
  .github/workflows/server-test.yml
  flake.lock
  flake.nix
Labels: bug, backend

#216 Link bloop Discord
  CONTRIBUTING.md
Labels: documentation
