Repository BloopAI/bloop, pull requests merged in 2023-10, with the labels that each got.

#1009 Fix invalid inclusion of stopwords
  server/bleep/src/agent.rs
  server/bleep/src/stopwords.txt
  stopwords.txt
Labels: bug

#1034 Send full redirect target to cognito
  server/bleep/src/webserver/aaa.rs
Labels: bug, backend

#1042 Fix race in credentials polling
  server/bleep/src/periodic/remotes.rs
Labels: bug, backend

#1038 Enable paid features for desktop users
  .github/workflows/server-test.yml
  Dockerfile
  apps/desktop/src-tauri/Cargo.toml
  client/src/components/PageTemplate/BranchSelector.tsx
  server/bleep/Cargo.toml
  server/bleep/src/background.rs
  server/bleep/src/ee.rs
  server/bleep/src/ee/webserver.rs
  server/bleep/src/lib.rs
  server/bleep/src/periodic/remotes.rs
  server/bleep/src/semantic.rs
  server/bleep/src/semantic/embedder.rs
  server/bleep/src/webserver/aaa.rs
  server/bleep/src/webserver/config.rs
  server/bleep/src/webserver/middleware.rs
  server/bleep/src/webserver/quota.rs
  server/bleep/src/webserver/repos.rs
Labels: enhancement

#1040 Allow indexing of large files
  server/bleep/src/indexes/file.rs
  server/bleep/src/repo/iterator.rs
  server/bleep/src/repo/iterator/fs.rs
  server/bleep/src/repo/iterator/git.rs
Labels: backend

#1052 Remove failures from time management
  server/bleep/src/periodic/remotes.rs
Labels: bug

#1046 Prioritize removal of repositories in the queue
  server/bleep/src/background.rs
  server/bleep/src/background/notifyqueue.rs
Labels: backend

#1053 Remove tantivy global reader lock
  server/bleep/src/background/sync.rs
  server/bleep/src/indexes.rs
  server/bleep/src/indexes/file.rs
  server/bleep/src/lib.rs
  server/bleep/src/state.rs
  server/bleep/src/webserver/intelligence.rs
Labels: enhancement, backend

#1061 Check if index directory exists before deleting
  server/bleep/src/indexes.rs
Labels: bug

#1048 Don't use credentials to fetch public repos
  server/bleep/src/remotes.rs
  server/bleep/src/remotes/github.rs
Labels: bug, backend

#1060 Escape regex string in search-based ref/def navigation
  server/bleep/src/webserver/intelligence.rs
Labels: bug

#1062 Allow force indexing files in the app
  client/src/components/IdeNavigation/DirEntry.tsx
  client/src/components/IdeNavigation/index.tsx
  client/src/components/MarkdownWithCode/FolderChip.tsx
  client/src/components/RepositoryFiles/FileRow.tsx
  client/src/components/RepositoryFiles/index.tsx
  client/src/pages/RepoTab/Repository/RepositoryOverview.tsx
  client/src/pages/RepoTab/Repository/index.tsx
  client/src/pages/RepoTab/ResultFull/index.tsx
  server/bleep/src/indexes/file.rs
Labels: feature

#1065 Refresh cognito config from public API
  .github/workflows/tauri-release.yml
  apps/desktop/src-tauri/src/backend.rs
  server/bleep/src/config.rs
Labels: enhancement

#1057 Catch unwind file indexing iterator
  server/bleep/src/indexes/file.rs
Labels: bug

#1068 Improve error logging on status changes
  server/bleep/src/background/sync.rs
Labels: enhancement, backend

#1074 Synchronicity issues with login flows
  server/bleep/src/periodic/remotes.rs
  server/bleep/src/webserver/github.rs
Labels: bug, backend

#1078 Recover from network errors in `poll_for_oauth_token`
  server/bleep/src/webserver/github.rs
Labels: bug

#1080 Increase rlimit
  apps/desktop/src-tauri/src/qdrant.rs
Labels: bug

#1071 Improve qdrant logging to observe crashes in sentry
  apps/desktop/src-tauri/src/backend.rs
  apps/desktop/src-tauri/src/config.rs
  apps/desktop/src-tauri/src/main.rs
  apps/desktop/src-tauri/src/qdrant.rs
  client/src/context/providers/DeviceContextProvider.tsx
  server/bleep/Cargo.toml
  server/bleep/src/analytics.rs
  server/bleep/src/bin/bleep.rs
  server/bleep/src/lib.rs
Labels: backend

#1075 Use arrows to navigate between selected ranges in code studio
  client/src/components/CodeBlock/CodeFullSelectable/CodeContainer.tsx
  client/src/locales/en.json
  client/src/locales/es.json
  client/src/locales/ja.json
  client/src/locales/zh-CN.json
  client/src/pages/StudioTab/BlueChip.tsx
  client/src/pages/StudioTab/FilePanel/index.tsx
  client/src/pages/StudioTab/LinesBadge.tsx
Labels: frontend

#1088 Build binaries if building for cloud
  Dockerfile
  server/bleep/Cargo.toml
  server/bleep/src/lib.rs
Labels: bug, backend

#1070 Move tutorial questions to first message
  client/src/components/Chat/ChatBody/AllCoversations/index.tsx
  client/src/components/Chat/ChatBody/Conversation.tsx
  client/src/components/Chat/ChatBody/FirstMessage.tsx
  client/src/components/Chat/ChatBody/index.tsx
  client/src/components/Chat/ChatFooter/index.tsx
  client/src/components/Chat/index.tsx
  client/src/locales/en.json
  client/src/locales/es.json
  client/src/locales/ja.json
  client/src/locales/zh-CN.json
Labels: frontend

#1077 Disable back/forward keyboard navigation if user is typing
  client/src/components/CodeBlock/CodeFull/ExplainButton.tsx
  client/src/components/CodeBlock/CodeFull/index.tsx
  client/src/components/PageTemplate/Subheader.tsx
  client/src/utils/domUtils.ts
Labels: frontend

#1090 Update to non-symlinky git
  Cargo.lock
Labels: bug, backend, windows
